// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPRTqg2beAs1u7YRrLW8AhJ9MDYeZzwyM',
    appId: '1:4673619938:web:32f98ec6bc0ac7af1fdbbb',
    messagingSenderId: '4673619938',
    projectId: 'chat-app-76d8f',
    authDomain: 'chat-app-76d8f.firebaseapp.com',
    storageBucket: 'chat-app-76d8f.firebasestorage.app',
    measurementId: 'G-3S2Q0W7HT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARgUArpJYoLiitT8saG9O5VCGKHJLPSEw',
    appId: '1:4673619938:android:3242b715ac6f2c4c1fdbbb',
    messagingSenderId: '4673619938',
    projectId: 'chat-app-76d8f',
    storageBucket: 'chat-app-76d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8iEfGpw2WD0g32hjj4Ty9n1KldLJ10g',
    appId: '1:4673619938:ios:752d84ec86e466251fdbbb',
    messagingSenderId: '4673619938',
    projectId: 'chat-app-76d8f',
    storageBucket: 'chat-app-76d8f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8iEfGpw2WD0g32hjj4Ty9n1KldLJ10g',
    appId: '1:4673619938:ios:752d84ec86e466251fdbbb',
    messagingSenderId: '4673619938',
    projectId: 'chat-app-76d8f',
    storageBucket: 'chat-app-76d8f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPRTqg2beAs1u7YRrLW8AhJ9MDYeZzwyM',
    appId: '1:4673619938:web:dd4a49bb9fa41a8d1fdbbb',
    messagingSenderId: '4673619938',
    projectId: 'chat-app-76d8f',
    authDomain: 'chat-app-76d8f.firebaseapp.com',
    storageBucket: 'chat-app-76d8f.firebasestorage.app',
    measurementId: 'G-TYNF1JNQWX',
  );
}
